server:
  port: 8081

spring:
  application:
    name: "todo-api"
  datasource:
    url: jdbc:mysql://db-p0faj.pub-cdb.ntruss.com:3306/mydb?allowPublicKeyRetrieval=true
    username: semyung
    password: tpaud123$

  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect